---
logging:
  level: info
  path:
    general: /home/ebook/perlybook.log
CHI:
  cpan2ebook_webservice:
    driver: File
    root_dir: /home/ebook/tmp
  PerltutsCom:
    driver: File
    root_dir: /home/ebook/tmp
cache_expiration:
  seconds: 864000
mail:
  how: smtp
  howargs:
    - smtp.server.tld
    - AuthUser
    - smtpuser
    - AuthPass
    - smtppass
  from: from@address.tld
exception:
  from: exception@address.tld
  to: recipient@error.tld
  subject: an error occured
userblock_seconds: 2
tmp_dir: /home/ebook/tmp
reverse_proxy: 1
autocompletion_size: 12
optional_message: <br /><br /><br /><p><small>This website just came into the world. Please report any problems <a href='https://github.com/reneeb/cpan2ebook/issues'>here</a>.</small></p>
secret: mypassphrase
